# Big Test Cleaning and Visualization

Thise file in will load in the data from "THE BIG TEST" dataset whoch collects preference data on 24 beverages a session across several sessions over multiple years.

In [46]:
from dotenv import load_dotenv
import os
from pathlib import Path
import pandas as pd
from sqlalchemy import create_engine, text

## STEP 1: Connecting to the SQL database

In [47]:
# Setting paths to SQL server based on your local storage location
load_dotenv(r"C:\Users\thaug\culinary_preferences\.env") # Load tour own personal .env where personal strings are stored

# Checking to make sure that the connection works - should yield culinary_preferences
print(os.getenv("MYSQL_DATABASE"))

culinary_preferences

Format for example .env file:

MYSQL_HOST=localhost
MYSQL_USER=root
MYSQL_PASSWORD=YOUR_PASSWORD
MYSQL_DATABASE=culinary_preferences

RAW_DATA_DIR=C:\Users\YOUR_USER\culinary_preferences\data\raw
PROCESSED_DATA_DIR=C:\Users\YOUR_USER\culinary_preferences\data\processed

We then use the environment inputs to create an engine for the SQL database

In [48]:
engine = create_engine(
    f"mysql+mysqlconnector://"
    f"{os.getenv('MYSQL_USER')}:"
    f"{os.getenv('MYSQL_PASSWORD')}@"
    f"{os.getenv('MYSQL_HOST')}/"
    f"{os.getenv('MYSQL_DATABASE')}"
)  

# Testing that the enginve connection works - should yield (1,)
with engine.connect() as connection:
    result = connection.execute(text("SELECT 1"))
    print(result.fetchone())

(1,)

We then display the tables using pandas

In [49]:
tables = pd.read_sql(
    """
    SHOW TABLES;
    """,
    engine
)

tables

  Tables_in_culinary_preferences
0              beverage_rankings
1                  beverage_type
2                      beverages
3              country_of_origin
4                         people
5                          years

Showing the current schema of our database

In [50]:
schema = pd.read_sql(
    """
    SELECT
        table_name,
        column_name,
        data_type,
        is_nullable,
        column_key
    FROM information_schema.columns
    WHERE table_schema = 'culinary_preferences'
    ORDER BY table_name, ordinal_position;
    """,
    engine
)

schema

           TABLE_NAME           COLUMN_NAME DATA_TYPE IS_NULLABLE COLUMN_KEY
0   beverage_rankings                    id       int          NO        PRI
1   beverage_rankings               year_id       int          NO        MUL
2   beverage_rankings             person_id       int          NO        MUL
3   beverage_rankings         list_position       int          NO
4   beverage_rankings           beverage_id       int          NO        MUL
5   beverage_rankings                 score   decimal         YES
6       beverage_type                    id       int          NO        PRI
7       beverage_type    beverage_type_name   varchar          NO        UNI
8           beverages                    id       int          NO        PRI
9           beverages         beverage_name   varchar          NO        UNI
10          beverages      beverage_type_id       int         YES        MUL
11          beverages  country_of_origin_id       int         YES        MUL
12  country_of_origin                    id       int          NO        PRI
13  country_of_origin          country_name   varchar          NO        UNI
14             people                    id       int          NO        PRI
15             people                  name   varchar          NO
16              years                    id       int          NO        PRI
17              years          ranking_year       int          NO        UNI

Displaying the foreing keys connecting the tables

In [51]:
foreign_keys = pd.read_sql(
    """
    SELECT
        table_name,
        column_name,
        referenced_table_name,
        referenced_column_name
    FROM information_schema.key_column_usage
    WHERE table_schema = 'culinary_preferences'
      AND referenced_table_name IS NOT NULL;
    """,
    engine
)

foreign_keys

,TABLE_NAME,COLUMN_NAME,REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME
0,beverage_rankings,year_id,years,id
1,beverage_rankings,person_id,people,id
2,beverage_rankings,beverage_id,beverages,id
3,beverages,beverage_type_id,beverage_type,id
4,beverages,country_of_origin_id,country_of_origin,id

## STEP 2: Load in the data from the Excell sheets

In [52]:
# Setting variables
raw_folder = Path(os.getenv("RAW_DATA_DIR")) # Setting the raw folder
excel_file = raw_folder / "DEN STORE TESTEN.xlsx" # Name of the raw data file

In [53]:
# Loading in the data
data = pd.read_excel(excel_file, sheet_name=None)
data["2020"].head()

   Nummer                       ØL Matsiboy Torbz Hermz Nur Vedo  Gjennomsnitt
0  Nr. 1:       Ægir Happy Red Ale       50    50    20  49   18          37.4
1  Nr. 2:         Lofoten Pale Ale       48    47    28  45   33          40.2
2  Nr. 3:  Sour Suzy Berliner Weis       45    30    37  39   49          40.0
3  Nr. 4:            Nøisom juleøl       20    24    20  37   35          27.2
4  Nr. 5:            Kirin Ichiban       55    60    55  50   59          55.8

This yields a dictionary with all of the indiviudla sheets of the excel file

Since all of the data we are interested in are stored in teh one named withd year markigns we can use these tags to extract
the data we want.

In [54]:
data = {
    sheet_name: df
    for sheet_name, df in data.items()
    if sheet_name.isdigit() and len(sheet_name) == 4
}
data["2021"].head()

,Nummer,Alko,Matsiboy,Torbz,Hermz,Nur,Vedo,Gjennomsnitt,Unnamed: 8,Varians
0,Nr. 1:,San Miguel,53,48,55,65,59,56.0,NaN,Matsiboy
1,Nr. 2:,Singha Lager,45,40,42,51,47,45.0,NaN,Torbz
2,Nr. 3:,Hansa Lite Mango IPA,60,54,45,45,39,48.6,NaN,Hermz
3,Nr. 4:,ECD Ramp Pale Ale,50,45,25,55,23,39.6,NaN,Nur
4,Nr. 5:,Berent Jaktpils,43,28,42,39,52,40.8,NaN,Vedo

In [55]:
# Checking for the data types stored within each sheet
for year, df in data.items():
    print(f"\n===== {year} =====")
    
    for column in df.columns:
        print(f"\n--- {column} ---")
        print(df[column].map(type).value_counts())

===== 2020 =====

--- Nummer ---
Nummer
<class 'float'>    42
<class 'str'>      24
Name: count, dtype: int64

--- ØL ---
ØL
<class 'float'>    35
<class 'str'>      31
Name: count, dtype: int64

--- Matsiboy ---
Matsiboy
<class 'float'>    41
<class 'int'>      24
<class 'str'>       1
Name: count, dtype: int64

--- Torbz ---
Torbz
<class 'float'>    41
<class 'int'>      24
<class 'str'>       1
Name: count, dtype: int64

--- Hermz ---
Hermz
<class 'float'>    41
<class 'int'>      24
<class 'str'>       1
Name: count, dtype: int64

--- Nur ---
Nur
<class 'float'>    41
<class 'int'>      24
<class 'str'>       1
Name: count, dtype: int64

--- Vedo ---
Vedo
<class 'float'>    41
<class 'int'>      24
<class 'str'>       1
Name: count, dtype: int64

--- Gjennomsnitt ---
Gjennomsnitt
<class 'float'>    66
Name: count, dtype: int64

===== 2021 =====

--- Nummer ---
Nummer
<class 'float'>    42
<class 'str'>      24
Name: count, dtype: int64

--- Alko ---
Alko
<class 'float'>    35
<class 'str'>      31
Name: count, dtype: int64

--- Matsiboy ---
Matsiboy
<class 'float'>    52
<class 'int'>      13
<class 'str'>       1
Name: count, dtype: int64

--- Torbz ---
Torbz
<class 'float'>    47
<class 'int'>      18
<class 'str'>       1
Name: count, dtype: int64

--- Hermz ---
Hermz
<class 'float'>    40
<class 'int'>      25
<class 'str'>       1
Name: count, dtype: int64

--- Nur ---
Nur
<class 'float'>    41
<class 'int'>      24
<class 'str'>       1
Name: count, dtype: int64

--- Vedo ---
Vedo
<class 'float'>    41
<class 'int'>      24
<class 'str'>       1
Name: count, dtype: int64

--- Gjennomsnitt ---
Gjennomsnitt
<class 'float'>    66
Name: count, dtype: int64

--- Unnamed: 8 ---
Unnamed: 8
<class 'float'>    66
Name: count, dtype: int64

--- Varians ---
Varians
<class 'float'>    61
<class 'str'>       5
Name: count, dtype: int64

===== 2022 =====

--- Nummer ---
Nummer
<class 'float'>    42
<class 'str'>      24
Name: count, dtype: int64

--- Øl ---
Øl
<class 'float'>    35
<class 'str'>      31
Name: count, dtype: int64

--- Matsiboy ---
Matsiboy
<class 'float'>    40
<class 'int'>      25
<class 'str'>       1
Name: count, dtype: int64

--- Torbz ---
Torbz
<class 'float'>    65
<class 'str'>       1
Name: count, dtype: int64

--- Hermz ---
Hermz
<class 'float'>    40
<class 'int'>      25
<class 'str'>       1
Name: count, dtype: int64

--- Nur ---
Nur
<class 'float'>    41
<class 'int'>      24
<class 'str'>       1
Name: count, dtype: int64

--- Vedo ---
Vedo
<class 'float'>    41
<class 'int'>      19
<class 'str'>       6
Name: count, dtype: int64

--- Gjennomsnitt ---
Gjennomsnitt
<class 'float'>    66
Name: count, dtype: int64

--- Unnamed: 8 ---
Unnamed: 8
<class 'float'>    66
Name: count, dtype: int64

--- Varians ---
Varians
<class 'float'>    61
<class 'str'>       5
Name: count, dtype: int64

===== 2023 =====

--- Nummer ---
Nummer
<class 'float'>    42
<class 'str'>      24
Name: count, dtype: int64

--- Drank ---
Drank
<class 'str'>      34
<class 'float'>    32
Name: count, dtype: int64

--- Matsiboy ---
Matsiboy
<class 'float'>    37
<class 'int'>      25
<class 'str'>       4
Name: count, dtype: int64

--- Torbz ---
Torbz
<class 'float'>    37
<class 'int'>      25
<class 'str'>       4
Name: count, dtype: int64

--- Hermz ---
Hermz
<class 'float'>    37
<class 'int'>      25
<class 'str'>       4
Name: count, dtype: int64

--- Nur ---
Nur
<class 'float'>    37
<class 'int'>      25
<class 'str'>       4
Name: count, dtype: int64

--- Vedo ---
Vedo
<class 'float'>    37
<class 'int'>      25
<class 'str'>       4
Name: count, dtype: int64

--- Susanne ---
Susanne
<class 'float'>    36
<class 'int'>      26
<class 'str'>       4
Name: count, dtype: int64

--- Colleen ---
Colleen
<class 'float'>    37
<class 'int'>      25
<class 'str'>       4
Name: count, dtype: int64

--- Raul ---
Raul
<class 'float'>    37
<class 'int'>      25
<class 'str'>       4
Name: count, dtype: int64

--- Sondre ---
Sondre
<class 'float'>    37
<class 'int'>      25
<class 'str'>       4
Name: count, dtype: int64

--- Gjennomsnitt ---
Gjennomsnitt
<class 'float'>    66
Name: count, dtype: int64

--- Ranking ---
Ranking
<class 'float'>    66
Name: count, dtype: int64

--- Beer ---
Beer
<class 'float'>    63
<class 'str'>       3
Name: count, dtype: int64

--- Standardavvik ---
Standardavvik
<class 'float'>    66
Name: count, dtype: int64

--- Max-Min ---
Max-Min
<class 'float'>    66
Name: count, dtype: int64

--- Unnamed: 16 ---
Unnamed: 16
<class 'float'>    66
Name: count, dtype: int64

--- Unnamed: 17 ---
Unnamed: 17
<class 'float'>    66
Name: count, dtype: int64

--- Unnamed: 18 ---
Unnamed: 18
<class 'float'>    66
Name: count, dtype: int64

--- Unnamed: 19 ---
Unnamed: 19
<class 'float'>    62
<class 'str'>       4
Name: count, dtype: int64

--- Unnamed: 20 ---
Unnamed: 20
<class 'float'>    62
<class 'str'>       4
Name: count, dtype: int64

--- Unnamed: 21 ---
Unnamed: 21
<class 'float'>    62
<class 'str'>       4
Name: count, dtype: int64

--- Unnamed: 22 ---
Unnamed: 22
<class 'float'>    62
<class 'str'>       4
Name: count, dtype: int64

--- Unnamed: 23 ---
Unnamed: 23
<class 'float'>    62
<class 'str'>       4
Name: count, dtype: int64

--- Unnamed: 24 ---
Unnamed: 24
<class 'float'>    62
<class 'str'>       4
Name: count, dtype: int64

--- Unnamed: 25 ---
Unnamed: 25
<class 'float'>    60
<class 'str'>       6
Name: count, dtype: int64

--- Unnamed: 26 ---
Unnamed: 26
<class 'float'>    62
<class 'str'>       4
Name: count, dtype: int64

--- Unnamed: 27 ---
Unnamed: 27
<class 'float'>    62
<class 'str'>       4
Name: count, dtype: int64

===== 2024 =====

--- Nummer ---
Nummer
<class 'float'>    42
<class 'str'>      24
Name: count, dtype: int64

--- Drank ---
Drank
<class 'str'>      34
<class 'float'>    32
Name: count, dtype: int64

--- Matsiboy ---
Matsiboy
<class 'float'>    36
<class 'int'>      26
<class 'str'>       4
Name: count, dtype: int64

--- Torbz ---
Torbz
<class 'float'>    37
<class 'int'>      25
<class 'str'>       4
Name: count, dtype: int64

--- Hermz ---
Hermz
<class 'float'>    37
<class 'int'>      25
<class 'str'>       4
Name: count, dtype: int64

--- Nur ---
Nur
<class 'float'>    64
<class 'int'>       1
<class 'str'>       1
Name: count, dtype: int64

--- Vedo ---
Vedo
<class 'float'>    66
Name: count, dtype: int64

--- Colleen ---
Colleen
<class 'float'>    37
<class 'int'>      25
<class 'str'>       4
Name: count, dtype: int64

--- Gjennomsnitt ---
Gjennomsnitt
<class 'float'>    66
Name: count, dtype: int64

--- Ranking ---
Ranking
<class 'float'>    66
Name: count, dtype: int64

--- Beer ---
Beer
<class 'float'>    64
<class 'str'>       2
Name: count, dtype: int64

--- Standardavvik ---
Standardavvik
<class 'float'>    66
Name: count, dtype: int64

--- Max-Min ---
Max-Min
<class 'float'>    66
Name: count, dtype: int64

--- Unnamed: 13 ---
Unnamed: 13
<class 'float'>    66
Name: count, dtype: int64

--- Unnamed: 14 ---
Unnamed: 14
<class 'float'>    66
Name: count, dtype: int64

--- Unnamed: 15 ---
Unnamed: 15
<class 'float'>    66
Name: count, dtype: int64

--- Unnamed: 16 ---
Unnamed: 16
<class 'float'>    62
<class 'str'>       4
Name: count, dtype: int64

--- Unnamed: 17 ---
Unnamed: 17
<class 'float'>    61
<class 'str'>       5
Name: count, dtype: int64

--- Unnamed: 18 ---
Unnamed: 18
<class 'float'>    62
<class 'str'>       4
Name: count, dtype: int64

--- Unnamed: 19 ---
Unnamed: 19
<class 'float'>    65
<class 'str'>       1
Name: count, dtype: int64

--- Unnamed: 20 ---
Unnamed: 20
<class 'float'>    61
<class 'str'>       5
Name: count, dtype: int64

===== 2025 =====

--- Nummer ---
Nummer
<class 'float'>    42
<class 'str'>      24
Name: count, dtype: int64

--- Drank ---
Drank
<class 'str'>      34
<class 'float'>    32
Name: count, dtype: int64

--- Matsiboy ---
Matsiboy
<class 'float'>    35
<class 'int'>      27
<class 'str'>       4
Name: count, dtype: int64

--- Torbz ---
Torbz
<class 'float'>    37
<class 'int'>      25
<class 'str'>       4
Name: count, dtype: int64

--- Hermz ---
Hermz
<class 'float'>    37
<class 'int'>      25
<class 'str'>       4
Name: count, dtype: int64

--- Nur ---
Nur
<class 'float'>    37
<class 'int'>      25
<class 'str'>       4
Name: count, dtype: int64

--- Vedo ---
Vedo
<class 'float'>    37
<class 'int'>      25
<class 'str'>       4
Name: count, dtype: int64

--- Gjennomsnitt ---
Gjennomsnitt
<class 'float'>    66
Name: count, dtype: int64

--- Ranking ---
Ranking
<class 'float'>    66
Name: count, dtype: int64

--- Beer ---
Beer
<class 'float'>    63
<class 'str'>       3
Name: count, dtype: int64

--- Standardavvik ---
Standardavvik
<class 'float'>    66
Name: count, dtype: int64

--- Max-Min ---
Max-Min
<class 'float'>    66
Name: count, dtype: int64

--- Unnamed: 12 ---
Unnamed: 12
<class 'float'>    66
Name: count, dtype: int64

--- Unnamed: 13 ---
Unnamed: 13
<class 'float'>    66
Name: count, dtype: int64

--- Unnamed: 14 ---
Unnamed: 14
<class 'float'>    66
Name: count, dtype: int64

--- Unnamed: 15 ---
Unnamed: 15
<class 'float'>    60
<class 'str'>       6
Name: count, dtype: int64

--- Unnamed: 16 ---
Unnamed: 16
<class 'float'>    62
<class 'str'>       4
Name: count, dtype: int64

--- Unnamed: 17 ---
Unnamed: 17
<class 'float'>    62
<class 'str'>       4
Name: count, dtype: int64

--- Unnamed: 18 ---
Unnamed: 18
<class 'float'>    62
<class 'str'>       4
Name: count, dtype: int64

--- Unnamed: 19 ---
Unnamed: 19
<class 'float'>    62
<class 'str'>       4
Name: count, dtype: int64

--- Unnamed: 20 ---
Unnamed: 20
<class 'float'>    65
<class 'str'>       1
Name: count, dtype: int64

--- Unnamed: 21 ---
Unnamed: 21
<class 'float'>    65
<class 'str'>       1
Name: count, dtype: int64

--- Unnamed: 22 ---
Unnamed: 22
<class 'float'>    65
<class 'str'>       1
Name: count, dtype: int64

--- Unnamed: 23 ---
Unnamed: 23
<class 'float'>    65
<class 'str'>       1
Name: count, dtype: int64

We then filter and clean the dataframe so that only the relevatn parts of the sheet is inlcuded and that the data is in the right format

In [56]:
# Doing dataframe level filtering
for year, df in data.items():
    data[year] = df[df["Nummer"].apply(lambda x: isinstance(x, str))] # Only selectign rows where there is a string with the order number of the beverage - and not an NaN value or some such

for year, df in data.items():
    df.rename(columns={df.columns[1]: "Beverage"}, inplace=True)
    df = df.loc[:, ~df.columns.str.contains("^Unnamed")] # Removing all empty columns
    columns_to_remove = ["Nummer", "Gjennomsnitt", "Varians", "Beer", "Ranking", "Standardavvik", "Max-Min"] # Creating a list of columns we want removed
    df = df.drop(columns= columns_to_remove, errors = "ignore") # Removing columns contatining non-participant information
    data[year] = df

Inspecting the dataframes

In [57]:
# Year we want to inspect
example_year = "2020"

In [58]:
data[example_year].tail()

                Beverage Matsiboy Torbz Hermz Nur Vedo
19        Ringnes Juleøl       30    25    30  25   48
20   Kinn Vestkyst India       48    45    50  45   38
21  St. Austell Proper J       35    50    29  35   27
22         London Porter       20    25    69  45   69
23      Boon Oude Geuze!       20    18    40  30   38

In [59]:
data[example_year].columns

Index(['Beverage', 'Matsiboy', 'Torbz', 'Hermz', 'Nur', 'Vedo'], dtype='str')

In [60]:
data[example_year].shape

(24, 6)

Mapping them into a dataframe structure compatible with our SQL server

In [61]:
list_of_long_dfs = []
for year, df in data.items():
    # List position
    df["list_position"] = range(1, len(df) + 1)

    # Making long format
    long_df = df.melt(
        id_vars=["Beverage", "list_position"],
        var_name="person",
        value_name="score"
    )

    # Adding year number
    long_df["ranking_year"] = year
    list_of_long_dfs.append(long_df)
long_df = pd.concat(list_of_long_dfs)
long_df.head()

                  Beverage  list_position    person score ranking_year
0       Ægir Happy Red Ale              1  Matsiboy    50         2020
1         Lofoten Pale Ale              2  Matsiboy    48         2020
2  Sour Suzy Berliner Weis              3  Matsiboy    45         2020
3            Nøisom juleøl              4  Matsiboy    20         2020
4            Kirin Ichiban              5  Matsiboy    55         2020

# Synchronizing With the SQL Database

In [62]:
# Inspecting who is stored in the people table
people = pd.read_sql(
    "SELECT * FROM people",
    engine
)

people

Empty DataFrame
Columns: [id, name]
Index: []

In [63]:
# Inspecting how many values we have in the years table
years = pd.read_sql(
    "SELECT * FROM years",
    engine
)

years

Empty DataFrame
Columns: [id, ranking_year]
Index: []

In [64]:
# Inspecting how many beverage names are saved
beverages = pd.read_sql(
    "SELECT * FROM beverages",
    engine
)

beverages

Empty DataFrame
Columns: [id, beverage_name, beverage_type_id, country_of_origin_id]
Index: []

In [66]:
pd.read_sql("DESCRIBE years", engine)
pd.read_sql("DESCRIBE people", engine)
pd.read_sql("DESCRIBE beverages", engine)

                  Field         Type Null  Key Default           Extra
0                    id          int   NO  PRI    None  auto_increment
1         beverage_name  varchar(50)   NO  UNI    None
2      beverage_type_id          int  YES  MUL    None
3  country_of_origin_id          int  YES  MUL    None

We then map our dataframe variables unto our SQL tables